import Head from 'next/head';
import { FollowCursor } from '@/ui/components/FollowCursor/FollowCursor';
import { AboutMe } from '@/ui/components/AboutMe/AboutMe';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container-fluid">
          <AboutMe />
          <FollowCursor />
        </div>
      </main>
    </>
  );
}
